apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::137039441913:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-P5D398VN8X42
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::137039441913:role/UdacityFlaskDeployCBKubectlRole
      username:build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-12-23T15:24:18Z"
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:mapRoles: {}
          f:mapUsers: {}
      manager: eksctl.exe
      operation: Update
      time: "2020-12-23T15:24:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1341"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 8bc284d7-335c-4bee-9928-c042a389e3be
