apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::137039441913:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1XSERAOY7WKNY
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::137039441913:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-12-24T08:43:06Z"
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:mapRoles: {}
          f:mapUsers: {}
      manager: eksctl.exe
      operation: Update
      time: "2020-12-24T08:43:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1489"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 7eb76fc8-eedc-4f5a-96fc-600f3a5926bc
