apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::137039441913:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1R5XDC7JSI4GO
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::137039441913:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-12-23T20:00:42Z"
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:mapRoles: {}
          f:mapUsers: {}
      manager: eksctl.exe
      operation: Update
      time: "2020-12-23T20:00:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1459"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: dee9f42a-0b71-4bdf-af85-13c7dfb10e0d
